language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: PrPbOqHvq4SYU1Bsvw1RfrofRWrdQVA46GtRAlb7Bt1/0qkk8jlowxLyUQVypSMLP4rsYGvPsCt3t7XjSUZfZkHqHiI1jecsf4qaQ0scKNdG+mnG5pCsa4+w42GRYtUQkpNnnZGqfObtYUFwurx4d3zMgy1bNEZAvslKB+2Op5UPghxFc/fPHAY9JTXOzBMwY9Gj8mmMr57pfEHF0k8PlZCa5IGv8snHpQA/9/wlvuAkURnbCJd5QLCLU0rrCEVq15CTgVPVjEuMMmyzfji2D66N52O0jO974tSMLDMTzmymRI9e/n8cv+s5gxu41i4h8OthINWnAqYfGXgK+VuuNLZozIXaCubzlwZus9B3SBnMjiX0ZZkqFoYq6a17783oaOfOQkHSYNrzsOb4xDGDhSXdY6Xyy+4w9MJ5ofN1s7bsKmTI85PY4VMT/nYnlCsR31iAjaoDQhTVpocgnt0dZMIfa95x/GXLXsIb/6YfjOpct12Xm0QUT6H1EIY7+y70Hfc3COPjx+Zb7RgSblpKXEkU85Yo3TOx4hEDzQkm3uQfWiLIbDzPQ5ipDvk0heVZ6ykVKdDff702qPU1U4h2qbeEoqKKVuAlgtv+4WjCDd1azbsNZaDimBDiYt1w9+oQgii7PVkFBpL/dVczlr2AhimpisGPkf76zT6Tkr6BLbY=
  app: son-linebot-v1
